apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "openstackIronicStandalone.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.api.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "openstackIronicStandalone.api.fullname" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "openstackIronicStandalone.name" . }}
        component: "{{ .Values.api.name }}"
        release: {{ .Release.Name }}
      name: {{ template "openstackIronicStandalone.api.fullname" . }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      template:
        metadata:
          labels:
            app: {{ template "openstackIronicStandalone.name" . }}
            component: "{{ .Values.api.name }}"
            release: {{ .Release.Name }}
      containers:
        - name: {{ template "openstackIronicStandalone.name" . }}-{{ .Values.api.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- with .Values.api.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
          command:
            - /bin/sh
          args:
            - -c
            - mako-render /etc/ironic/ironic.conf.mako >/tmp/ironic.conf; /usr/bin/ironic-api --config-file /tmp/ironic.conf
          env:
            - name: API_PORT_INTERNAL
              value: {{ .Values.api.portInternal }}
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstackIronicStandalone.name" . }}-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstackIronicStandalone.name" . }}-rabbitmq
                  key: rabbitmq-erlang-cookie
            {{- end }}
            {{- if .Values.mysql.enabled }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstackIronicStandalone.name" . }}-mysql
                  {{- if .Values.mysql.mysqlUser }}
                  key: mysql-password
                  {{- else }}
                  key: mysql-root-password
                  {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.api.portInternal }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          ports:
            - name: "ironic-api-port"
              containerPort: {{ .Values.api.portInternal }}
          volumeMounts:
            - mountPath: /etc/ironic
              name: ironic-etc
              readOnly: true
      volumes:
        - name: ironic-etc
          configMap:
            name: {{ template "openstackIronicStandalone.name" . }}-etc
            defaultMode: 0644
