apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "openstackIronicStandalone.conductor.fullname" . }}
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    component: {{ .Values.conductor.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.conductor.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "openstackIronicStandalone.name" . }}
        component: {{ .Values.conductor.name }}
        release: {{ .Release.Name }}
      name: {{ include "openstackIronicStandalone.conductor.fullname" . }}
      annotations:
        configmap-etc-hash: {{ include (print $.Template.BasePath "/etc-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ include "openstackIronicStandalone.conductor.fullname" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- with .Values.conductor.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
          command:
            - /usr/bin/ironic-conductor
          args:
            - --config-file
            - /etc/ironic/ironic.conf
          env:
            - name: IRONIC_URL
              value: "{{ include "openstackIronicStandalone.api.fullname" . }}:{{ .Values.api.portExternal }}/"
            - name: OS_AUTH_TOKEN
              value: "fake-token"
#          livenessProbe:
#            exec:
#              command:
#                - /bin/bash
#                - -c
#                - ironic driver-list | grep "$HOSTNAME"
#            initialDelaySeconds: 30
#            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /storage
              name: ironic
            - mountPath: /etc/ironic
              name: ironic-etc
              readOnly: true
      initContainers:
        - name: wait-for-mysql
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          command:
            - /bin/sh
          args:
            - -c
            - mako-render /tmp/wait-for-mysql.sh.mako >/tmp/wait-for-mysql.sh; chmod +x /tmp/wait-for-mysql.sh; /tmp/wait-for-mysql.sh
          env:
            - name: MYSQL_PASSWORD
            {{- if .Values.mysql.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstackIronicStandalone.name" . }}-mysql
                  {{- if .Values.mysql.mysqlUser }}
                  key: mysql-password
                  {{- else }}
                  key: mysql-root-password
                  {{- end }}
            {{- else }}
              value: {{ .values.mysql.mysqlPassword }}
            {{- end }}
          volumeMounts:
            - mountPath: /tmp/wait-for-mysql.sh.mako
              name: ironic-db-scripts
              subPath: wait-for-mysql.sh
              readOnly: true
        - name: update-database-schema
          image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
          command: 
            - ironic-dbsync
            - --config-file
            - /etc/ironic/ironic.conf
            - upgrade
          volumeMounts:
            - mountPath: /etc/ironic
              name: ironic-etc
              readOnly: true
      volumes:
        - name: ironic-etc
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-etc
            defaultMode: 0644
        - name: ironic-db-scripts
          configMap:
            name: {{ include "openstackIronicStandalone.name" . }}-db-scripts
            defaultMode: 0755
        - name: ironic
          persistentVolumeClaim:
            {{- if .Values.persistentVolumeClaimName }}
            claimName: {{ .Values.persistentVolumeClaimName | quote }}
            {{- else }}
            claimName: {{ ( include "openstackIronicStandalone.tftp.fullname" . ) | quote }}
            {{- end }}
