apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstackIronicStandalone.name" . }}-etc
  labels:
    app: {{ include "openstackIronicStandalone.name" . }}
    chart: {{ include "openstackIronicStandalone.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ironic.conf.mako: |
{{ include (print .Template.BasePath "/etc/_ironic.conf.tpl") . | indent 4 }}
{{ (.Files.Glob "static-config/*").AsConfig | indent 2 }}
