{{- range $index, $entry := tuple .Values.api.name .Values.httpboot.name }}
{{- if (index $.Values $entry).ingress.enabled -}}
{{- $ingressPath := (index $.Values $entry).ingress.path -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include (printf "openstackIronicStandalone.%v.fullname" $entry) $ }}
  labels:
    app.kubernetes.io/name: {{ include "openstackIronicStandalone.name" $ }}
    helm.sh/chart: {{ include "openstackIronicStandalone.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
{{- with (index $.Values $entry).ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (index $.Values $entry).ingress.tls }}
  tls:
  {{- range (index $.Values $entry).ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range (index $.Values $entry).ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ include (printf "openstackIronicStandalone.%v.fullname" $entry) $ }}
              servicePort: {{ (printf "ironic-%v\n" $entry) }}
  {{- end }}
{{- end }}
{{- end }}
